name: Deploy to GCP VM and manage firewall

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify VM access (list VMs)
        run: |
          gcloud compute instances list \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --filter="name=${{ secrets.GCP_VM_NAME }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_LOG: DEBUG

      - name: Terraform Apply
        run: terraform apply -auto-approve
